### PR TITLE
Threading and error handling improvements

### PR DESCRIPTION
**Pull request by aleks-tpom6oh**

### CODE REVIEW

**Review by kristleifur — APPROVED** [review]
This makes sense! Caveat: I don't know the specifics of how the exclusivity locking works, only that this is a block-scoped kind of thread-safety mechanism, right? – I'm quite ignorant of Objective-C details (this is ObjC, right? 😅).

... but everything makes perfect sense in general!

**Review by logason — APPROVED** [review]
LGTM!

**Comment by aleks-tpom6oh** [comment]
@kristleifur Objective-C, one of the most beautiful programming languages imo, it's like French of programming languages. 😄

**Comment by kristleifur** [comment]
It does speak to its qualities that a change like this was super pleasant to read 💡

**Pull request merged**
